LibraryAccounting/Pages/ClientPages/BookCatalog.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using LibraryAccounting.Infrastructure.Handlers;
using LibraryAccounting.Domain.Interfaces.PocessingRequests;
using LibraryAccounting.Domain.Model;
using LibraryAccounting.Domain.ToolInterfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryAccounting.Pages.ClientPages
{
    public class BookCatalogModel : PageModel
    {
        public Dictionary<Book, bool> Books { get; set; }
        readonly private IClientTools ClientTools;
        public int ClientId { get; set; }
        public SelectList Authors { get; set; }
        public SelectList Genres { get; set; }
        public SelectList Publishers { get; set; }

        public BookCatalogModel(IClientTools clientTools, IHttpContextAccessor httpContext)
        {
            ClientTools = clientTools;
            if (httpContext.HttpContext.User.Identity.IsAuthenticated)
                ClientId = Convert.ToInt32(httpContext.HttpContext.User.Claims.ElementAt(2).Value);

            var authors = ClientTools.GetAllBooks().Select(b => b.Author).Distinct();
            Authors = new SelectList(authors);

            var genres = ClientTools.GetAllBooks().Select(b => b.Genre).Distinct();
            Genres = new SelectList(genres);

            var publishers = ClientTools.GetAllBooks().Select(b => b.Publisher).Distinct();
            Publishers = new SelectList(publishers);
        }

        public void OnGet()
        {
            Books = new BookCatalogHandler().Handle(ClientTools.GetAllBooks(), ClientTools.GetAllBookings());
        }

        public void OnPost(string author, string genre, string publisher)
        {
            var decorator = new DecoratorHandler<Book>(
                new List<IRequestsHandlerComponent<Book>>()
                {new BooksByAuthorHandler(author),
                new BooksByGenreHandler(genre),
                new BooksByPublisherHandler(publisher)
                });

            var books = ClientTools.GetBooks(decorator);
            Books = new BookCatalogHandler().Handle(books, ClientTools.GetAllBookings());
        }
    }
}

LibraryAccounting/Pages/LibrarianPages/BookCatalog.cshtml.cs
using System.Collections.Generic;
using System.IO;
using System.Linq;
using LibraryAccounting.Infrastructure.Handlers;
using LibraryAccounting.Domain.Interfaces.PocessingRequests;
using LibraryAccounting.Domain.Model;
using LibraryAccounting.Domain.ToolInterfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace LibraryAccounting.Pages.LibrarianPages
{
    public class BookCatalogModel : PageModel
    {
        readonly ILibrarianTools LibrarianTools;
        readonly private IWebHostEnvironment Environment;
        public Dictionary<Book, bool> Books;
        public Dictionary<int, User> Users;
        public Dictionary<int, Booking> Bookings;
        public SelectList Authors { get; set; }
        public SelectList Genres { get; set; }
        public SelectList Publishers { get; set; }

        public BookCatalogModel(ILibrarianTools librarianTools, IWebHostEnvironment environment)
        {
            LibrarianTools = librarianTools;
            Environment = environment;

            var authors = LibrarianTools.GetAllBooks().Select(b => b.Author).Distinct();
            Authors = new SelectList(authors);

            var genres = LibrarianTools.GetAllBooks().Select(b => b.Genre).Distinct();
            Genres = new SelectList(genres);

            var publishers = LibrarianTools.GetAllBooks().Select(b => b.Publisher).Distinct();
            Publishers = new SelectList(publishers);
        }

        public void OnGet()
        {
            Initialize();
        }

        public void OnGetRemove(int id)
        {
            var book = LibrarianTools.GetBook(id);
            string path = "/img/" + book.Title + ".jpg";
            FileInfo file = new FileInfo(Environment.WebRootPath + path);
            file.Delete();
            LibrarianTools.RemoveBook(book);
            Initialize();
        }

        public void OnPost(string author, string genre, string publisher)
        {
            var decorator = new DecoratorHandler<Book>(
                new List<IRequestsHandlerComponent<Book>>()
                {new BooksByAuthorHandler(author),
                new BooksByGenreHandler(genre),
                new BooksByPublisherHandler(publisher)
                });

            var books = LibrarianTools.GetBooks(decorator);
            Initialize(books);
        }

        private void Initialize(IEnumerable<Book> books = null)
        {
            if (books == null)
            {
                books = LibrarianTools.GetAllBooks();
            }
            Books = new BookCatalogHandler().Handle(books, LibrarianTools.GetAllBookings());
            Users = new UsersWidthIdHandler().Handle(LibrarianTools.GetAllUsers());
            Bookings = new BookingsWidthBookIdHandler().Handle(LibrarianTools.GetAllBookings());
        }
    }
}

LibraryAccounting/Pages/LibrarianPages/BookForm.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LibraryAccounting.Domain.Model;
using LibraryAccounting.Domain.ToolInterfaces;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LibraryAccounting.Pages.LibrarianPages
{
    public class BookFormModel : PageModel
    {
        readonly private ILibrarianTools LibrarianTools;
        readonly private IWebHostEnvironment Environment;
        public Book Book { get; set; }
        public BookFormModel(ILibrarianTools librarianTools, IWebHostEnvironment environment)
        {
            LibrarianTools = librarianTools;
            Environment = environment;
            Book = new Book();
        }

        public void OnGet(int? id)
        {
            if (id != null)
            {
                Book = LibrarianTools.GetBook(Convert.ToInt32(id));
            }
        }

        public async Task<IActionResult> OnPost(Book book, IFormFile cover)
        {
            if(cover != null)
            if (ModelState.IsValid)
            {
                string path = "/img/" + book.Title + ".jpg";
                using(var fileStream = new FileStream(Environment.WebRootPath + path, FileMode.Create))
                {
                    await cover.CopyToAsync(fileStream);
                }
                LibrarianTools.AddBook(book);
                return RedirectToPage("/LibrarianPages/BookCatalog");
            }
            return RedirectToPage("/LibrarianPages/BookForm");
        }
    }
}

LibraryAccounting/Pages/LibrarianPages/BookCatalog.cshtml
@page
@model LibraryAccounting.Pages.LibrarianPages.BookCatalogModel
@{
    ViewData["LibrarianPages/BookCatalog"] = "disabled";
}
<div class="container mt-3">
    <form class="form-inline" method="post">
        <div class="form-group">
            <label class="m-2">Автор: </label>
            <select name="author" class="form-control" asp-items="Model.Authors">
                <option value="emtpy">Пусто</option>
            </select>
        </div>
        <div class="form-group">
            <label class="m-2">Жанр: </label>
            <select name="genre" class="form-control" asp-items="Model.Genres">
                <option value="emtpy">Пусто</option>
            </select>
        </div>
        <div class="form-group">
            <label class="m-2">Издатель: </label>
            <select name="publisher" class="form-control" asp-items="Model.Publishers">
                <option value="emtpy">Пусто</option>
            </select>
        </div>
        <button class="btn btn-info m-2" type="submit">Фильтровать</button>
    </form>
    <div class="row justify-content-md-start">
        @foreach (var book in Model.Books)
        {
            <div class="col-lg-3 col-md-2 col-12">
                <a>
                    <h4>@book.Key.Title</h4>
                    <p>Автор: @book.Key.Author <br />Жанр: @book.Key.Genre <br />Издатель: @book.Key.Publisher</p>
                </a>
                @if (book.Value)
                {
                    <p>В наличии</p>
                    <a class="btn btn-warning booking-btn" asp-page="BookForm" asp-route-id="@book.Key.Id">Редактировать</a>
                    <a class="btn btn-warning booking-btn" asp-page-handler="Remove" asp-route-id="@book.Key.Id">Удалить</a>
                }
                else
                {
                    <p>Забронировано @Model.Users[Model.Bookings[book.Key.Id].ClientId].Name @Model.Bookings[book.Key.Id].BookingDate</p>
                    if (Model.Bookings[book.Key.Id].IsTransmitted)
                    {
                        <p>Передано @Model.Bookings[book.Key.Id].TransferDate</p>
                        if (Model.Bookings[book.Key.Id].IsReturned)
                        {
                            <p>Принято @Model.Bookings[book.Key.Id].ReturnDate</p>
                        }
                        else
                        {
                            <a class="btn btn-info booking-btn">Принять</a>
                        }
                    }
                    else
                    {
                        <p>Не передано</p>
                        <a class="btn btn-danger booking-btn">Передать</a>
                    }
                }
            </div>
        }
    </div>
</div>

LibraryAccounting/Pages/LibrarianPages/BookForm.cshtml
@page
@model LibraryAccounting.Pages.LibrarianPages.BookFormModel
@{
    ViewData["LibrarianPages/BookForm"] = "disabled";
}
<div class="container mt-3">
    <div class="row justify-content-center">
        <div class="col-5">
            <form method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label>Название</label>
                    <input type="text" class="form-control" asp-for="@Model.Book.Title" />
                </div>
                <div class="form-group">
                    <label>Автор</label>
                    <input type="text" class="form-control" asp-for="@Model.Book.Author" />
                </div>
                <div class="form-group">
                    <label>Издатель</label>
                    <input type="text" class="form-control" asp-for="@Model.Book.Publisher" />
                </div>
                <div class="form-group">
                    <label>Жанр</label>
                    <input type="text" class="form-control" asp-for="@Model.Book.Genre" />
                </div>
                <div class="form-group">
                    <label>Обложка</label>
                    <input type="file" name="cover" class="form-control-file" />
                </div>
                <button type="submit" class="btn btn-dark">Отправить</button>
            </form>
        </div>
    </div>
</div>

LibraryAccounting/Pages/LibrarianPages/_LibrarianLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryAccounting</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/client/client.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">LibraryAccounting</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link @ViewData["LibrarianPages/BookCatalog"]" asp-page="/LibrarianPages/BookCatalog">Каталог книг</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @ViewData["LibrarianPages/BookedBooks"]" asp-page="/LibrarianPages/BookedBooks">Забронированные книги</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link @ViewData["LibrarianPages/BookForm"]" asp-page="/LibrarianPages/BookForm">Добавить книгу</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-page="/Index">Выйти</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - LibraryAccounting - <a asp-area="" asp-page="/Privacy">Конфиденциальность</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>